### ISSUE TITLE
Bug - On Email Validation, Validation Works but Shows 500 Error

### ISSUE THREAD

**Issue by GoodGameGabe** [hernanjkd/swapprofit-beta#1]
### **ON CLICK:**
<img width="645" alt="Screen Shot 2020-08-10 at 4 12 06 PM" src="https://user-images.githubusercontent.com/41083088/89826463-4586f700-db24-11ea-91e5-e9d2f82e28fc.png">

### **REDIRECTS TO:**
<img width="459" alt="Screen Shot 2020-08-10 at 4 12 14 PM" src="https://user-images.githubusercontent.com/41083088/89826474-49b31480-db24-11ea-9ced-c9c22a182f7b.png">

###  **EXPECTED RESULT:** 
{"message":"YOU EMAIL HAS BEEN VALIDATED"}

**Comment by hernanjkd** [comment]
Tested by Gabe and me.. closing issue
